name: Deploy to firebase

on:
  push:
    branches:
      - main
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install

      - name: Install firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to firebase
        run: |
          # Determine the Firebase Hosting Channel based on the branch name
          if [ "${{ github.ref }}" = "refs/heads/main"]; then
          CHANNEL="main"
          elif [ "${{ github.ref }}" = "refs/heads/prod"];
          CHANNEL="prod"
          else
          # If the branch is not main or prod, exit without deploying
          echo "Branch does not exist."
          exit 0
          fi

          # Deploy your application to specified Hosting Channel
          firebase hosting:channel:deploy "$CHANNEL" --token "$FIREBASE_TOKEN"
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
