name: Deploy to firebase

on:
  push:
    branches:
      - main
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: npm install

      - name: Install firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to firebase
        run: |
          # Deploy your app to Firebase hosting
          firebase use myapp && firebase deploy --only hosting:prod --token "$FIREBASE_TOKEN"
        env: 
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
